source: "./"
safe: true
lsi: false
pygments: true
markdown: rdiscount
url: "http://theodinproject.github.io/curriculum" # FOR PRODUCTION
# url: "http://localhost:4000" # FOR LOCAL TESTING
nav:
  - # Introduction
    -
      - "Introduction"
      - "/"
  - # Becoming A Web Developer
    - 
      - "About Web Developers"
      - "/dir/becoming_a_web_developer/"
  - # Installations
    - 
      - Installations
      - "/dir/installations/"
  - # Pairing
    - 
      - Pair Programming
      - "/dir/pairing/"      
  - # Web Development 101
    -
      - "Web Development 101"
      - "/dir/web_development_basics"
    -
      - "How Does the Web Work?"
      - "/dir/web_development_basics/how_does_the_web_work.html"
    -
      - "How Does Your Computer Work?"
      - "/dir/web_development_basics/how_does_your_computer_work.html"
    -
      - "Terms To Know"
      - "dir/web_development_basics/terms_to_know.html"
    -
      - "Web Programming Basics"
      - "dir/web_development_basics/web_programming_basics.html"
    -
      - "And so on.............."
      - " "
  -  # Ruby
    - 
      - Ruby
      - "/dir/ruby/"
    - 
      - Basic Ruby Project 1
      - "/dir/ruby/projects/basic_ruby_project_1.html"
    - 
      - Basic Ruby Project 2
      - "/dir/ruby/projects/basic_ruby_project_2.html"
    -
      - "File I/O Project"
      - "/dir/ruby/projects/file_io_project.html"
    -
      - "OOP Project"
      - "/dir/ruby/projects/oop_project.html"
    -
      - "Recursion Project"
      - "/dir/ruby/projects/recursion_project.html"
    - 
      - "Data Structures and Algorithms Project"
      - "/dir/ruby/projects/data_structures_algorithms_project.html"
    -
      - "Testing Project"
      - "/dir/ruby/projects/testing_project.html"
    -
      - "Ruby on the Web Project"
      - "/dir/ruby/projects/ruby_web_project.html"
    -
      - "Ruby Final Project"
      - "/dir/ruby/projects/ruby_final_project.html"
  - # Git
    - 
      - "Git (Coming Soon!)"
      - "/dir/git/"
  - # Databases
    - 
      - "Databases (Coming Soon!)"
      - "/dir/databases/"
  - # Ruby on Rails
    -
      - "Ruby on Rails (Coming Soon!)"
      - "/dir/rails/"
  - # HTML / CSS
    -
      - "HTML / CSS (Coming Soon!)"
      - "/dir/html_css/"
  - # Javascript
    -
      - "Javascript (Coming Soon!)"
      - "/dir/javascript/"
  - # Tying It All Together
    -
      - "Tying it All Together (Coming Soon!)"
      - "/dir/tying_it_all_together/"
